name: stanford-stages
channels:
  - defaults
dependencies:
  - h5py=2.8.0
  - hdf5=1.10.2
  - numpy=1.15.3
  - python=3.6.7
  - scipy=1.1.0
  - pip:
    - pyedflib==0.1.12
    - scikit-learn==0.19.1
    - xmltodict==0.11.0
